services:
  channel:
    build: ./channel
    environment:
      - PER=${PER}

  receiver:
    build: ./receiver

  sender:
    build: ./sender
    user: root
    environment:
      - PER=${PER}
    volumes:
      - "./results:/results"
    depends_on:
      - channel
